apiVersion: v1
kind: Namespace
metadata:
  name: nodeapp
  labels:
    name: nodeapp
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: stvcontreg1.azurecr.io/nodeapp:2020-12-14
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: nodeapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    # targetPort: 8080
  selector:
      app: nodeapp
